version: 2.1
orbs:
  architect: giantswarm/architect@6.0.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          name: "package and push outgoing-proxy-stack chart"
          app_catalog: "cluster-catalog"
          app_catalog_test: "cluster-test-catalog"
          chart: "outgoing-proxy-stack"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
